"""
controlsurfaces

Contains definitions for basic control surface types, which can be extended by
controllers if necessary.

Authors:
* Miguel Guthridge [hdsq@outlook.com.au, HDSQ#2154]
"""

__all__ = [
    # Base types
    'ControlSurface',
    'IControlShadow',
    'ControlShadow',
    'NullControlShadow',
    'ControlShadowList',
    # Control mappings
    'IControlHash',
    'ControlMapping',
    'ControlEvent',
    'ControlShadowEvent',
    # Other imports
    'value_strategies',
    'event_patterns',
    # Control surfaces
    'NullEvent',
    'Note',
    'ModWheel',
    'PitchWheel',
    'StandardModWheel',
    'StandardPitchWheel',
    'Data2PitchWheel',
    'AfterTouch',
    'ChannelAfterTouch',
    'NoteAfterTouch',
    'Pedal',
    'SustainPedal',
    'SostenutoPedal',
    'SoftPedal',
    'Button',
    'TransportButton',
    'PlayButton',
    'StopButton',
    'LoopButton',
    'RecordButton',
    'FastForwardButton',
    'RewindButton',
    'MetronomeButton',
    'NavigationControl',
    'NavigationButton',
    'DpadButtons',
    'DirectionUp',
    'DirectionDown',
    'DirectionLeft',
    'DirectionRight',
    'DirectionSelect',
    'NextPrevButton',
    'DirectionNext',
    'DirectionPrevious',
    'JogWheel',
    'StandardJogWheel',
    'ShiftedJogWheel',
    'MoveJogWheel',
    'Fader',
    'MasterFader',
    'FaderButton',
    'GenericFaderButton',
    'MasterGenericFaderButton',
    'MuteButton',
    'MasterMuteButton',
    'SoloButton',
    'MasterSoloButton',
    'ArmButton',
    'MasterArmButton',
    'SelectButton',
    'MasterSelectButton',
    'Knob',
    'MasterKnob',
    'Encoder',
    'ModXY',
    'ModX',
    'ModY',
    'DrumPad',
    'MacroButton',
    'SaveButton',
    'UndoRedoButton',
    'UndoButton',
    'RedoButton',
    'QuantizeButton',
    'CaptureMidiButton',
    'SwitchActiveButton',
    'SwitchActivePluginButton',
    'SwitchActiveWindowButton',
    'SwitchActiveToggleButton',
    'PauseActiveButton',
    'ControlSwitchButton',
    'HintMsg',
    'NotifMsg',
]

from .controls import (
    ControlSurface,
    NullEvent,
    Note,
    ModWheel,
    PitchWheel,
    StandardModWheel,
    StandardPitchWheel,
    Data2PitchWheel,
    AfterTouch,
    ChannelAfterTouch,
    NoteAfterTouch,
    Pedal,
    SustainPedal,
    SostenutoPedal,
    SoftPedal,
    Button,
    ControlSwitchButton,
    TransportButton,
    PlayButton,
    StopButton,
    LoopButton,
    RecordButton,
    FastForwardButton,
    RewindButton,
    MetronomeButton,
    NavigationControl,
    NavigationButton,
    DpadButtons,
    DirectionUp,
    DirectionDown,
    DirectionLeft,
    DirectionRight,
    DirectionSelect,
    NextPrevButton,
    DirectionNext,
    DirectionPrevious,
    JogWheel,
    StandardJogWheel,
    ShiftedJogWheel,
    MoveJogWheel,
    Fader,
    MasterFader,
    FaderButton,
    GenericFaderButton,
    MasterGenericFaderButton,
    MuteButton,
    MasterMuteButton,
    SoloButton,
    MasterSoloButton,
    ArmButton,
    MasterArmButton,
    SelectButton,
    MasterSelectButton,
    Knob,
    MasterKnob,
    Encoder,
    ModXY,
    ModX,
    ModY,
    DrumPad,
    MacroButton,
    SaveButton,
    UndoRedoButton,
    UndoButton,
    RedoButton,
    QuantizeButton,
    CaptureMidiButton,
    SwitchActiveButton,
    SwitchActivePluginButton,
    SwitchActiveWindowButton,
    SwitchActiveToggleButton,
    PauseActiveButton,
    HintMsg,
    NotifMsg,
)

from .control_shadow import (
    IControlShadow,
    ControlShadow,
    NullControlShadow,
    ControlShadowList,
)
from .control_mapping import (
    IControlHash,
    ControlMapping,
    ControlEvent,
    ControlShadowEvent
)

from . import value_strategies
from . import event_patterns
