"""
controlsurfaces > controlshadow

Represents a "shadow" control surface, which can be modified as necessary
without affecting the original control, unless it is specifically applied

Authors:
* Miguel Guthridge [hdsq@outlook.com.au, HDSQ#2154]
"""
from common.types import Color
from .controlmapping import ControlMapping
from . import ControlSurface

class ControlShadow:
    """
    A class representing a MIDI event mapped to a control surface

    Subclasses of this object should be generated by device modules, so that it
    can then be processed by plugin modules.
    """
    
    def __init__(self, control: ControlSurface) -> None:
        """
        Create an event object

        This should be called when recognising an event

        ### Args:
        * `control` (`ControlSurface`): control associated with this event
        """
        self.__control = control
        self.__value = control.value
        self.__color = control.color.copy()
        self.__annotation = control.annotation

    def getControl(self):
        """
        Get a reference to the control surface associated with the event

        ### Returns:
        * `ControlSurface`: control surface
        """
        return self.__control
    
    def getMapping(self) -> ControlMapping:
        return self.__control.getMapping()
    
    def getCurrentValue(self) -> float:
        """
        Returns the value currently applied to this control.
        
        NOTE: This differs from the value which will be applied to the control,
        which is stored in the `value` property.

        ### Returns:
        * `float`: value of the event (0 - 1.0)
        """
        return self.__control.value

    @property
    def value(self) -> float:
        """
        Represents the value that will be applied to the control after
        the event has been processed, as a float between 0-1
        """
        return self.__value
    @value.setter
    def value(self, newVal: float) -> None:
        if not (0 <= newVal <= 1):
            raise ValueError("Value must be within range 0-1")
        self.__value = newVal
    
    @property
    def color(self) -> Color:
        """
        Represents the color that will be applied to the control after the event
        has been processed.
        """
        return self.__color
    @color.setter
    def color(self, newColor: Color) -> None:
        self.__color = newColor

    @property
    def annotation(self) -> str:
        """
        Represents the annotation that will be applied to the control after the
        event has been processed.
        """
        return self.__annotation
    @annotation.setter
    def annotation(self, newAnnotation: str) -> None:
        self.__annotation = newAnnotation
    
    @property
    def group(self) -> str:
        """
        The group that the control is in
        """
        return self.__control.group

    def apply(self) -> None:
        """
        Apply the configuration of the control shadow to the control it represents
        """
        self.__control.color = self.color
        self.__control.annotation = self.annotation
        self.__control.value = self.value
