name: Build project

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Copy other required files
      run: |
        cp README.md src/README.md
        cp LICENSE src/LICENSE
    - uses: actions/upload-artifact@v4
      with:
        name: 'UniversalController'
        path: src
